import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Container from "@/components/aetherium/Container";

import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-black bg-cover xl:bg-[url('/images/Trevin-13.jpg')]`}>
        <Container className="overflow-y-scroll h-full border-4 border-white  xl:w-1/3 xl:mx-auto xl:border-0 xl:shadow-lg xl:shadow-black text-white">
          {children}
        </Container>
      </body>
    </html>
  );
}
