import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Trevin & Carisa | Two Become One – May 16 2026",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-black`}>{children}</body>
    </html>
  );
}
